// read-only but not immutable

export const TAO_HEADERS = {
    1: 'The Mystical Way',
    2: 'The Unity of Opposites',
    3: 'Simplicity',
    4: 'Inscrutability',
    5: 'Creative Emptiness',
    6: 'The Mystical Female',
    7: 'Everlasting Unselfishness',
    8: 'Flexibility without Competition',
    9: 'Letting Go',
    10: 'Purity and Modesty',
    11: 'Creative Nothingness',
    12: 'Unaddicted Harmony',
    13: 'Autonomous Self-Esteem',
    14: 'The Incomprehensibility of Dào',
    15: 'The Inscrutability of the Wise Men',
    16: 'Returning to Constancy',
    17: 'Considerate Leadership',
    18: 'The Omen of Decay',
    19: 'Freedom through Modesty',
    20: 'Profane Men and Wise Men',
    21: 'Unfathomable Dào',
    22: 'The Wisdom of Yieldingness',
    23: 'The Sustainability of Dào',
    24: 'Avoidance of Sophistication',
    25: 'The Greatness of Dào',
    26: 'Serenity',
    27: 'True Mastership',
    28: 'Visionary Power',
    29: 'Non-Intervention',
    30: 'The Power of Ahimsa',
    31: 'Victories for Peace',
    32: 'Transcendency',
    33: 'Enlightenment',
    34: 'Unselfish Grandeur',
    35: 'Incorruptibility',
    36: 'The Power of the Paradox',
    37: 'The Victory of Contentedness',
    38: 'The Power of Non-Intentionality',
    39: 'Harmony through Simplicity',
    40: 'Returning to Non-Being',
    41: 'Unimposing Dào',
    42: 'Non-Violent Evolution',
    43: 'The Victory of Softness',
    44: 'True Values',
    45: 'The Paradox of Truth',
    46: 'Peaceful Frugality',
    47: 'Perception and Insight',
    48: 'Less is More!',
    49: 'Goodness and Faithfulness as Examples',
    50: 'Death and Life',
    51: 'The Way and its Power',
    52: 'Sense and Sensuousness',
    53: 'Right Way and Going Astray',
    54: 'Social Maturing',
    55: 'The Power of Virtue',
    56: 'Silent Enlightenment',
    57: 'Silent Simplicity, Noble Greatness!',
    58: 'Gentle Leadership',
    59: 'Moderation',
    60: 'Domination without Damage',
    61: 'First Servants',
    62: 'Source and Refuge',
    63: 'The Lightness of Being',
    64: 'First Steps to Completion',
    65: 'Plain Naturalness',
    66: 'Leading from Below',
    67: 'The Three Treasures',
    68: 'True Leadership',
    69: 'Victorious Retreat',
    70: 'But Few are Chosen',
    71: 'Illusion and Wisdom',
    72: 'True Authority',
    73: 'Tacit Victories',
    74: 'Death and Deadliness',
    75: 'Tax Riots',
    76: 'Subtle Strengths',
    77: 'The Way of Nature',
    78: 'The Wisdom of Water',
    79: 'The Blessing of Tolerance',
    80: 'Simplify Your Life!',
    81: 'True Words',
};
